[package]
name = "simple"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
client = {path = "../../client"}
env_logger = "0.10.1"
tokio = { version = "1.34.0", features = ["full"] }
